### ISSUE TITLE
This plugin is very convenient! But every time I restart obsidian, it will become invalid and the values ​​need to be readjusted. Is it possible to save the fixed settings?

### ISSUE THREAD

**Issue by kiradzS** [nicosomb/obsidian-shrink-pinned-tabs#4]

**Comment by nicosomb** [comment]
Hello @kiradzS 

Thank you for your message. 
could you please send me screenshots or a video to see what happens ?

**Comment by platnub** [comment]
> Hello @kiradzS
> 
> Thank you for your message. could you please send me screenshots or a video to see what happens ?

If I understood kiradzS correctly, I am having the same issue.

When closing and reopening Obsidian, the tabs are regular size. You need to disable and enabled the plugin for the tabs to shrink again.

**Comment by ryanwwest** [comment]
Same here, and when 'Hide tab title' is enabled, if I click the tab it sometimes doesn't open the tab but displays only the 'x' icon to close the pinned tab. Would be nice to hide the x altogether and require a right click to close the tab.

**Comment by nicosomb** [comment]
Sorry for this bug. 
I don't have time for now to fix it. 

If someone wants to open a pull request ... 😊
